<?php

namespace App\Imports;

use App\Models\Asset;
use App\Models\AssetCategory;
use App\Models\AssetDepreciationSchedule;
use App\Models\Branch;
use App\Models\Company;
use App\Services\Asset\AssetDepreciationCalculator;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

/**
 * Bulk-import opening-balance assets.
 *
 * For each row we create the Asset record (code is auto-generated by the
 * model observer) and then generate AssetDepreciationSchedule rows for the
 * REMAINING useful life — past months are recorded as already-processed so
 * the batch depreciation UI only picks up future periods. The opening GL
 * (DR Asset / DR Accum.Depr / CR Opening Equity) is the user's responsibility
 * and should be entered as a single per-category journal.
 */
class AssetsImport implements ToCollection, WithHeadingRow
{
    private const ALLOWED_TYPES = ['tangible', 'intangible'];

    private const ALLOWED_ACQ_TYPES = ['outright_purchase', 'financed_purchase', 'leased', 'rented'];

    private const ALLOWED_METHODS = ['straight-line', 'declining-balance', 'units-of-production', 'sum-of-years-digits', 'no-depreciation'];

    private const ALLOWED_STATUSES = ['active', 'inactive', 'disposed', 'sold', 'scrapped', 'written_off'];

    /** @var string[] */
    public array $errors = [];

    public int $created = 0;

    public int $schedulesCreated = 0;

    public function collection(Collection $rows): void
    {
        if ($rows->isEmpty()) {
            $this->errors[] = 'Berkas kosong atau tidak memiliki baris data.';

            return;
        }

        $companiesByName = Company::query()->get()->keyBy(fn ($c) => mb_strtolower($c->name));
        $branches = Branch::query()->with('branchGroup')->get();
        $branchesByCompanyAndName = [];
        foreach ($branches as $b) {
            $key = $b->branchGroup?->company_id.'|'.mb_strtolower($b->name);
            $branchesByCompanyAndName[$key] = $b;
        }
        $categoriesByCode = AssetCategory::query()->get()->keyBy('code');

        $singleCompany = $companiesByName->count() === 1 ? $companiesByName->first() : null;

        $staged = [];
        foreach ($rows as $index => $row) {
            $lineNo = $index + 2;
            $name = trim((string) ($row['nama'] ?? ''));
            if ($name === '') {
                continue;
            }

            $companyName = trim((string) ($row['perusahaan'] ?? ''));
            $company = $companyName !== ''
                ? $companiesByName->get(mb_strtolower($companyName))
                : $singleCompany;
            if (! $company) {
                $msg = $companyName !== '' ? "'{$companyName}' tidak ditemukan" : 'wajib diisi (lebih dari satu perusahaan tersedia)';
                $this->errors[] = "Baris {$lineNo}, kolom 'perusahaan': {$msg}.";

                continue;
            }

            $branchName = trim((string) ($row['cabang'] ?? ''));
            if ($branchName === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'cabang': wajib diisi.";

                continue;
            }
            $branch = $branchesByCompanyAndName[$company->id.'|'.mb_strtolower($branchName)] ?? null;
            if (! $branch) {
                $this->errors[] = "Baris {$lineNo}, kolom 'cabang': '{$branchName}' tidak ditemukan untuk perusahaan '{$company->name}'.";

                continue;
            }

            $categoryCode = trim((string) ($row['kategori_kode'] ?? ''));
            if ($categoryCode === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'kategori_kode': wajib diisi.";

                continue;
            }
            $category = $categoriesByCode->get($categoryCode);
            if (! $category) {
                $this->errors[] = "Baris {$lineNo}, kolom 'kategori_kode': '{$categoryCode}' tidak ditemukan.";

                continue;
            }

            $type = mb_strtolower(trim((string) ($row['tipe'] ?? 'tangible')));
            if ($type === '') {
                $type = 'tangible';
            }
            if (! in_array($type, self::ALLOWED_TYPES, true)) {
                $this->errors[] = "Baris {$lineNo}, kolom 'tipe': harus salah satu dari ".implode(', ', self::ALLOWED_TYPES).'.';

                continue;
            }

            $acqType = mb_strtolower(trim((string) ($row['tipe_perolehan'] ?? 'outright_purchase')));
            if ($acqType === '') {
                $acqType = 'outright_purchase';
            }
            if (! in_array($acqType, self::ALLOWED_ACQ_TYPES, true)) {
                $this->errors[] = "Baris {$lineNo}, kolom 'tipe_perolehan': harus salah satu dari ".implode(', ', self::ALLOWED_ACQ_TYPES).'.';

                continue;
            }

            $acqDate = $this->parseDate($row['tanggal_perolehan'] ?? null);
            if ($acqDate === null) {
                $this->errors[] = "Baris {$lineNo}, kolom 'tanggal_perolehan': wajib diisi dengan format tanggal yang valid (mis. 2024-01-31).";

                continue;
            }

            $costBasis = $row['nilai_perolehan'] ?? null;
            if (! is_numeric($costBasis) || (float) $costBasis < 0) {
                $this->errors[] = "Baris {$lineNo}, kolom 'nilai_perolehan': harus berupa angka >= 0.";

                continue;
            }
            $costBasis = (float) $costBasis;

            $salvage = $row['nilai_residu'] ?? 0;
            if ($salvage === '' || $salvage === null) {
                $salvage = 0;
            }
            if (! is_numeric($salvage) || (float) $salvage < 0) {
                $this->errors[] = "Baris {$lineNo}, kolom 'nilai_residu': harus berupa angka >= 0.";

                continue;
            }
            $salvage = (float) $salvage;

            $method = mb_strtolower(trim((string) ($row['metode_penyusutan'] ?? 'straight-line')));
            if ($method === '') {
                $method = 'straight-line';
            }
            if (! in_array($method, self::ALLOWED_METHODS, true)) {
                $this->errors[] = "Baris {$lineNo}, kolom 'metode_penyusutan': harus salah satu dari ".implode(', ', self::ALLOWED_METHODS).'.';

                continue;
            }

            $usefulLife = $row['umur_bulan'] ?? null;
            if ($usefulLife === '' || $usefulLife === null) {
                $usefulLife = 0;
            }
            if (! is_numeric($usefulLife) || (int) $usefulLife < 0) {
                $this->errors[] = "Baris {$lineNo}, kolom 'umur_bulan': harus berupa angka >= 0.";

                continue;
            }
            $usefulLife = (int) $usefulLife;

            $deprStart = $this->parseDate($row['tanggal_mulai_penyusutan'] ?? null) ?? $acqDate;

            $accumDepr = $row['akumulasi_penyusutan'] ?? 0;
            if ($accumDepr === '' || $accumDepr === null) {
                $accumDepr = 0;
            }
            if (! is_numeric($accumDepr) || (float) $accumDepr < 0) {
                $this->errors[] = "Baris {$lineNo}, kolom 'akumulasi_penyusutan': harus berupa angka >= 0.";

                continue;
            }
            $accumDepr = (float) $accumDepr;
            if ($accumDepr > max(0.0, $costBasis - $salvage)) {
                $this->errors[] = "Baris {$lineNo}, kolom 'akumulasi_penyusutan': tidak boleh melebihi (nilai_perolehan - nilai_residu).";

                continue;
            }

            $status = mb_strtolower(trim((string) ($row['status'] ?? 'active')));
            if ($status === '') {
                $status = 'active';
            }
            if (! in_array($status, self::ALLOWED_STATUSES, true)) {
                $this->errors[] = "Baris {$lineNo}, kolom 'status': harus salah satu dari ".implode(', ', self::ALLOWED_STATUSES).'.';

                continue;
            }

            $warranty = null;
            if (! empty($row['garansi_sampai'])) {
                $warranty = $this->parseDate($row['garansi_sampai']);
                if ($warranty === null) {
                    $this->errors[] = "Baris {$lineNo}, kolom 'garansi_sampai': format tanggal tidak valid.";

                    continue;
                }
            }

            $isAmortizable = $type === 'intangible';
            $isDepreciable = ! $isAmortizable && $method !== 'no-depreciation';

            $staged[] = [
                'company_id' => $company->id,
                'branch_id' => $branch->id,
                'asset_category_id' => $category->id,
                'name' => $name,
                'type' => $type,
                'acquisition_type' => $acqType,
                'acquisition_date' => $acqDate->toDateString(),
                'cost_basis' => $costBasis,
                'salvage_value' => $salvage,
                'is_depreciable' => $isDepreciable,
                'is_amortizable' => $isAmortizable,
                'depreciation_method' => $method,
                'useful_life_months' => $usefulLife,
                'depreciation_start_date' => $deprStart->toDateString(),
                'accumulated_depreciation' => $accumDepr,
                'net_book_value' => max(0.0, $costBasis - $accumDepr),
                'status' => $status,
                'warranty_expiry' => $warranty?->toDateString(),
                'notes' => trim((string) ($row['catatan'] ?? '')) ?: null,
            ];
        }

        if (! empty($this->errors)) {
            return;
        }

        DB::transaction(function () use ($staged) {
            $userGlobalId = Auth::user()?->global_id;

            foreach ($staged as $row) {
                $asset = Asset::create(array_merge($row, [
                    'created_by' => $userGlobalId,
                    'updated_by' => $userGlobalId,
                ]));

                $this->created++;

                if (! $asset->is_depreciable && ! $asset->is_amortizable) {
                    continue;
                }
                if ($row['useful_life_months'] <= 0) {
                    continue;
                }

                $this->schedulesCreated += $this->createForwardSchedules(
                    $asset,
                    (float) $row['cost_basis'],
                    (float) $row['salvage_value'],
                    (int) $row['useful_life_months'],
                    (string) $row['depreciation_method'],
                    Carbon::parse($row['depreciation_start_date']),
                    (float) $row['accumulated_depreciation'],
                );
            }
        });
    }

    /**
     * Create AssetDepreciationSchedule rows starting from the first month
     * whose cumulative amount exceeds $accumDepr. Earlier months are skipped
     * (treated as already booked against the opening balance).
     */
    private function createForwardSchedules(
        Asset $asset,
        float $cost,
        float $salvage,
        int $months,
        string $method,
        Carbon $startDate,
        float $accumDepr,
    ): int {
        $amounts = AssetDepreciationCalculator::amounts($method, $cost, $salvage, $months);
        if (empty($amounts)) {
            return 0;
        }

        // Find the first sequence index whose cumulative amount strictly exceeds
        // the user-supplied accumulated depreciation. That's where future schedules begin.
        $cumulative = 0.0;
        $skip = 0;
        foreach ($amounts as $i => $amt) {
            $cumulative += $amt;
            if ($cumulative > $accumDepr + 0.01) {
                $skip = $i;
                break;
            }
            $skip = $i + 1;
        }

        $dayOfMonth = (int) $startDate->day;
        $created = 0;
        for ($i = $skip; $i < $months; $i++) {
            $date = $startDate->copy();
            $date->day = 1;
            $date->addMonths($i);
            $date->day = min($dayOfMonth, $date->daysInMonth);

            AssetDepreciationSchedule::create([
                'asset_id' => $asset->id,
                'sequence_number' => $i + 1,
                'schedule_date' => $date->toDateString(),
                'amount' => $amounts[$i],
                'method' => $method,
                'is_processed' => false,
            ]);
            $created++;
        }

        return $created;
    }

    private function parseDate(mixed $value): ?Carbon
    {
        if ($value === null || $value === '') {
            return null;
        }

        if (is_numeric($value)) {
            try {
                $unix = (int) round(((float) $value - 25569) * 86400);

                return Carbon::createFromTimestampUTC($unix)->startOfDay();
            } catch (\Throwable) {
                return null;
            }
        }

        try {
            return Carbon::parse((string) $value)->startOfDay();
        } catch (\Throwable) {
            return null;
        }
    }
}
