<?php

namespace App\Imports;

use App\Models\Company;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\TaxCategory;
use App\Models\Uom;
use App\Services\Catalog\ProductAppService;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

/**
 * Bulk-create inventory-tracked goods_stock products.
 *
 * Variants are auto-generated by ProductAppService based on the chosen
 * category's attribute set. For categories whose attribute set has no
 * variant axes, a single default variant is created with SKU = product code.
 */
class ProductsImport implements ToCollection, WithHeadingRow
{
    /** @var string[] */
    public array $errors = [];

    public int $created = 0;

    public function __construct(
        private readonly ProductAppService $productService,
    ) {}

    public function collection(Collection $rows): void
    {
        if ($rows->isEmpty()) {
            $this->errors[] = 'Berkas kosong atau tidak memiliki baris data.';

            return;
        }

        $categoriesByCode = ProductCategory::query()->get()->keyBy('code');
        $uomsByCode = Uom::query()->get()->keyBy('code');
        $taxCategoriesByCode = TaxCategory::query()->get()->keyBy('code');
        $existingByCode = Product::query()->pluck('code')->map(fn ($c) => true)->toArray();
        $companyIds = Company::query()->pluck('id')->toArray();

        $staged = [];
        foreach ($rows as $index => $row) {
            $lineNo = $index + 2;
            $code = trim((string) ($row['kode'] ?? ''));
            $name = trim((string) ($row['nama'] ?? ''));

            if ($code === '' && $name === '') {
                continue;
            }

            if ($code === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'kode': wajib diisi.";

                continue;
            }
            if ($name === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'nama': wajib diisi.";

                continue;
            }
            if (isset($staged[$code]) || isset($existingByCode[$code])) {
                $this->errors[] = "Baris {$lineNo}, kolom 'kode': nilai '{$code}' sudah dipakai.";

                continue;
            }

            $categoryCode = trim((string) ($row['kategori_kode'] ?? ''));
            if ($categoryCode === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'kategori_kode': wajib diisi.";

                continue;
            }
            $category = $categoriesByCode->get($categoryCode);
            if (! $category) {
                $this->errors[] = "Baris {$lineNo}, kolom 'kategori_kode': '{$categoryCode}' tidak ditemukan.";

                continue;
            }

            $uomCode = trim((string) ($row['satuan_kode'] ?? ''));
            if ($uomCode === '') {
                $this->errors[] = "Baris {$lineNo}, kolom 'satuan_kode': wajib diisi.";

                continue;
            }
            $uom = $uomsByCode->get($uomCode);
            if (! $uom) {
                $this->errors[] = "Baris {$lineNo}, kolom 'satuan_kode': '{$uomCode}' tidak ditemukan.";

                continue;
            }

            $taxCategory = null;
            $taxCode = trim((string) ($row['pajak_kode'] ?? ''));
            if ($taxCode !== '') {
                $taxCategory = $taxCategoriesByCode->get($taxCode);
                if (! $taxCategory) {
                    $this->errors[] = "Baris {$lineNo}, kolom 'pajak_kode': '{$taxCode}' tidak ditemukan.";

                    continue;
                }
            }

            $isActive = $this->parseBool($row['aktif'] ?? null, true);

            $staged[$code] = [
                'line' => $lineNo,
                'code' => $code,
                'name' => $name,
                'kind' => 'goods_stock',
                'cost_model' => 'inventory_layer',
                'product_category_id' => $category->id,
                'attribute_set_id' => $category->attribute_set_id,
                'default_uom_id' => $uom->id,
                'tax_category_id' => $taxCategory?->id,
                'is_active' => $isActive,
                'capabilities' => ['inventory_tracked'],
                'company_ids' => $companyIds,
                'attributes' => [],
            ];
        }

        if (! empty($this->errors)) {
            return;
        }

        DB::transaction(function () use ($staged) {
            foreach ($staged as $input) {
                $this->productService->createProduct($input, 'goods_stock');
                $this->created++;
            }
        });
    }

    private function parseBool(mixed $value, bool $default): bool
    {
        if ($value === null || $value === '') {
            return $default;
        }
        if (is_bool($value)) {
            return $value;
        }
        $normalized = mb_strtolower(trim((string) $value));

        return in_array($normalized, ['1', 'true', 'yes', 'y', 'ya', 'aktif'], true);
    }
}
